### PR TITLE
Migrated Properties to Single class

### LINKED ISSUE #28: Jfjfnjg

### LINKED ISSUE #30: Two panels
https://github.com/DesarrolloAntonio/TwoPanels/commit/eea94b1172871b29369dc12c34ce3da0394dabe8

### LINKED ISSUE #31: Shibuya
https://github.com/punchdrunker/shibuya/commit/97d71bf0d7fe2fdfac3ac6a5b659a9b3a404ae75

### PR DESCRIPTION
**Pull request by cybercoder-naj**
Adding custom fields to a modifier is not very clear with Jetpack Compose yet. Also, sending rating bar properties to composables like Row may be in violation of certain programming principles. Hence, I created a class similar to that of Modifier that encapsulates the different configurations of the RatingBar composable.

### CODE REVIEW

**Comment by cybercoder-naj** [comment]
This is in reference to Issue #14

**Comment by a914-gowtham** [comment]
Thanks, @cybercoder-naj for the effort. A request to keep the **value**  field outside like now how the library has. because, I followed [state hoisting pattern](https://developer.android.com/jetpack/compose/state#state-hoisting).  `value`,`onValueChange`, `onRatingChanged` fields are important field here. other fields can be added in the RatingBarConfig class including `ratingbarStyle`.

**Comment by cybercoder-naj** [comment]
I have implemented the state hoisting pattern in the composable function

**Comment by a914-gowtham** [comment]
Hi @cybercoder-naj  I will be pushing a release with compose version update to 1.0.5. afterward, I will merge and plan to release this PR.

**Comment by cybercoder-naj** [comment]
Hey @a914-gowtham I am already using compose version 1.0.5 for this project.

**Comment by a914-gowtham** [comment]
@cybercoder-naj this PR has breaking changes for existing library users. so, releasing a separate build for compose version update would be a good idea.

**Comment by a914-gowtham** [comment]
@cybercoder-naj  Thanks once again

**Pull request merged**
